// // // components/AdminLayout.jsx
// // import AdminSidebar from './AdminSidebar';

// // const AdminLayout = ({ children }) => {
// //   return (
// //     <div className="flex min-h-screen bg-gray-100">
// //       <AdminSidebar />
// //       <main className="flex-1 p-8">{children}</main>
// //     </div>
// //   );
// // };

// // export default AdminLayout;

// import type { Metadata } from "next";
// import "./globals.css";
// import "bootstrap-icons/font/bootstrap-icons.css"
// import {Inter} from "next/font/google"
// import AdminSidebar from "@/components/AdminSidebar";

// const inter = Inter({subsets:["latin"]})


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//     return (
//             <div className="flex min-h-screen bg-gray-100">
//               <AdminSidebar />
//               <main className="flex-1 p-8">{children}</main>
//             </div>
//           );
// }
